/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplyArrangement: typeof import('./src/components/ApplyArrangement.vue')['default']
    ManagerNavbar: typeof import('./src/components/ManagerNavbar.vue')['default']
    RequestLinks: typeof import('./src/components/RequestLinks.vue')['default']
    RequestTable: typeof import('./src/components/RequestTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleList: typeof import('./src/components/staff/ScheduleList.vue')['default']
    StaffNavbar: typeof import('./src/components/StaffNavbar.vue')['default']
    StaffTeamSchedule: typeof import('./src/components/StaffTeamSchedule.vue')['default']
    StatusButton: typeof import('./src/components/StatusButton.vue')['default']
  }
}
