name: Continuous Integration
run-name: CI checks for ${{ github.actor }} ${{ github.event_name }} on ${{ github.ref }} 🚀

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  inspect-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Compiler
        run: npm run build --if-present

      - name: Test
        run: npm test
