name: Continuous Integration
run-name: CI checks for ${{ github.actor }} ${{ github.event_name }} on ${{ github.ref }} 🚀

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  inspect-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Formatter
        run: npm run check

      - name: Decode Service Account JSON
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service-account.json

      - name: Run tests
        run: npm run test:ci

      - name: Clean up
        if: always()
        run: rm -f service-account.json