name: Continuous Integration (Test Backend)

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Install googleapis dependency from root
        run: npm install --prefix .. googleapis

      - name: Decode Service Account JSON
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > ../service-account.json

      - name: Run tests
        run: npm run test

      - name: Clean up
        if: always()
        run: rm -f ../service-account.json
